bolg/bolg/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import BlogListView , BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView
from django.views.generic.base import RedirectView

from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from . models import User
from django.contrib import admin

from django.views.static import serve
from django.urls import re_path
 
app_name='bolg'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',BlogListView.as_view(), name='homepage'),
    path('<int:pk>',BlogDetailView.as_view(), name='detail_url'),
    path('create/',BlogCreateView, name='create_url'),
    path('<int:pk>/update/',BlogUpdateView, name='update_url'),
    path('<int:pk>/delete',BlogDeleteView, name='delete_url'),
    path('favicon.ico/', RedirectView.as_view(url='/static/img/favicon.ico')),
    
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bolg/bolg/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse 

class Post(models.Model):
    title = models.CharField(max_length = 255)
    small_desc = models.TextField(max_length=400)   
    full_content = models.TextField()
    published_on = models.DateTimeField(auto_now_add = True)
    img = models.ImageField(upload_to='images/', blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    edited_on = models.DateTimeField(auto_now = True)
    likes = models.ManyToManyField(User, blank = True , related_name = 'likes')

    def get_absolute_url(self):
        return reverse('detail_url', kwargs={'pk':self.id})

    class Meta:
        ordering = ['-published_on']

bolg/bolg/forms.py
from django import forms 
from .models import Post 

class BlogModelForm(forms.ModelForm):
    #img = forms.ImageField()   this mistake almost killed me :( 

    class Meta:
        model = Post
        fields = [
            'title',
            'small_desc',
            'full_content',
            'img',
            
            ]
       

bolg/bolg/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse 
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    DeleteView,
    UpdateView,
    )

from .forms import BlogModelForm 

#def home(request):
#    post = Post.objects.all()
#    context = {
#        'post' : post            
#        }
#    return render(request, 'home.html',context)

class BlogListView(ListView):
    template_name = 'home.html'
    queryset = Post.objects.all()

class BlogDetailView(DetailView):
    template_name = 'detail.html'
    queryset = Post.objects.all()
    
    

    #def get_object(self):
    #    id_ = self.kwargs.get('id')
    #    return get_object_or_404(Post, id=id_)

#class BlogCreateView(CreateView):
#    template_name = 'create.html'
#    form_class = BlogModelForm
#    queryset = Post.objects.all() 

def BlogCreateView(request):
    form = BlogModelForm()
    if(request.method == 'POST'):
        form = BlogModelForm(request.POST, request.FILES )    
        print(request.FILES)
        if form.is_valid():
            form.save()
        return redirect('../../')

    context = {
        'form' : form
        }

    return render(request, 'create.html', context )



#class BlogUpdateView(UpdateView):
#    template_name = 'create.html'
#    form_class = BlogModelForm
#    queryset = Post.objects.all() 


def BlogUpdateView(request, pk):
    
    obj = get_object_or_404(Post, id=pk)
    form = BlogModelForm(instance = obj)
    if request.method=='POST':

        form = BlogModelForm(request.POST, request.FILES , instance = obj)
        
        if form.is_valid():
            form.save()
        return redirect('../../')
    
    
    context = {
        'form' : form,
        'obj' : obj
        }
    return render(request, 'update.html', context )
    





def BlogDeleteView(request, pk):
    obj = Post.objects.get(id=pk)
    print('\n\n\n')
    print(obj)
    if(request.method == "POST"):
        obj.delete()
        return redirect('/')
    context = { 
        'obj':obj
        }
    return render(request, 'delete.html', context)

bolg/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.min.css"
          integrity="sha512-17EgCFERpgZKcm0j0fEq1YCJuyAWdz9KUtv1EjVuaOz8pDnh/0nZxmU6BBXwaaxqoi9PQXnRWqlcDB027hgv9A=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css"
          integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% block head %}
    {% endblock %}
</head>
<body>

    {% block content %}
    hello
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"
            integrity="sha512-HGOnQO9+SP1V92SrtZfjqxxtLmVzqZpjFFekvzZVWoiASSQgSr4cw9Kqd2+l8Llp4Gm0G8GIFJ4ddwZilcdb8A=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>

</html>

bolg/templates/create.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<style>
    body {
        padding: 5%;
        background-color: #E1E6E7;
        /*overflow-y:hidden;*/
    }

    .div-1 {
        margin-inline: auto;
        width: 40vw;
        background-color: #E1E1E1;
        padding: 2%;
        border-radius: 2%;
        box-shadow: 0px 5px 20px 2px #888888;
    }
</style>
{% endblock %}
{% block content %}

<div class="header">
    <a href="/">
        <button type="button" class="btn btn-secondary float-end">Home</button>
    </a>
    <center>
        <h1 style=" padding-bottom:2%;">Create your blog</h1>
    </center>

</div>


<!--<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save" />
</form>-->


<!--formatted form-->


<div class="div-1">
    <form action=""  method="POST" enctype="multipart/form-data" >
        {% csrf_token %}
        <!--<input type="hidden" name="csrfmiddlewaretoken" value="sG1NCISUkpRLmkYCCyGtzJcvdbvrVZTmyJCMS0RFXAGDoQPMTJxt5weS6A60zyp2">-->
        <p><label for="id_title" class="col-sm-2 col-form-label">Title:</label> <input type="text" name="title" maxlength="255" required id="id_title"></p>
        <p>
            <label for="id_small_desc" class="col-sm-2 col-form-label">Small desc:</label> <textarea name="small_desc" cols="40" rows="5" maxlength="400" required id="id_small_desc">
        </textarea>
        </p>
        <p>
            <label for="id_full_content" class="col-sm-2 col-form-label">Full content:</label> <textarea name="full_content" cols="40" rows="5" required id="id_full_content">
    </textarea>
        </p>
        <p><label for="id_img" class="col-sm-2 col-form-label">Img:</label> <input type="file" name="img" accept="image/*" id="id_img"></p>
        <center><input type="submit" class="btn btn-success px-5 " value="Save" /></center>
    </form>
</div>


<!--<form action="." method="POST">
    <input type="hidden" name="csrfmiddlewaretoken" value="FfXCL4mN5UkMmNmpd7tXFInkSTmCZu3lLiyB1mlyI59EojdzuikXbvpHLiXbD3z1">

    <div class="mb-3 fieldWrapper">

        <label for="id_title">Title:</label> <input type="text" name="title" maxlength="255" required id="id_title">

    </div>

    <div class="mb-3 fieldWrapper">

        <label for="id_small_desc">Small desc:</label> <textarea name="small_desc" cols="40" rows="10" maxlength="400" required id="id_small_desc">
        </textarea>

    </div>

    <div class="mb-3 fieldWrapper">

        <label for="id_full_content">Full content:</label> <textarea name="full_content" cols="40" rows="10" required id="id_full_content">
        </textarea>

    </div>


    <div class="mb-3 fieldWrapper">

        <label for="id_img">Img:</label> <input type="file" name="img" accept="image/*" id="id_img">

    </div>

    <input type="submit" value="Save" />
</form>-->
{% endblock %}

bolg/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="POST" >{% csrf_token %}
    <h2>Do you want to delete this Blog?</h2>
    <p><input type="submit" value="Yes"/><a href="../">Cancel</a></p>

</form>
{% endblock %}

bolg/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<style>
    #header {
        margin: 2%;
    }

    body {
        margin: 4%;
        background-color: #CECECE;
    }

    #content {
        padding: 5%;
        padding-inline: 10%;
        font-size:13        0%;
    }
</style>
{% endblock %}

{% block content %}

<div class="header">
    <a href="/">
        <button type="button" class="btn btn-secondary float-end">Home</button>
    </a>
    <center>
        <h1 id="head">Blog</h1>
    </center>

</div>
<div id="header">
    <center>
        <h1>{{object.title|capfirst}}</h1>
    </center>
</div>
<div>
    <p>
        {{object.published_on|date:"D d M Y"}}
    </p>
    <p id="content">
        {{object.full_content}}
    </p>
    {% if object.img%}
    <center>
        <img src="{{object.img.url}}" width="500vw" height="400vw"/>
    </center>
    {% endif %}
    <div class="float-end">
        <h5>-By {{object.author|capfirst}}</h5>
    </div>

</div>

    



{% endblock %}

bolg/templates/home.html
{% extends 'base.html'%}
{% load static %}
{%block title%}
Homepage
{% endblock %}
{% block head %}
<style>
    body {
        background-color: #E8E8E8;
        padding: 5%;
    }

    #head {
        padding: 2%;
    }

    .my-row {
        max-height: 80vh;
    }

    .container {
        max-height: 10vw;
    }
    .img {
        position: absolute;
        width: 100%;
        height: 100%;
        opacity: 0.7;
        top: 0;
        bottom: 0;
        filter: blur(4px);
    }
   
</style>
<link rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.min.css"
      integrity="sha512-17EgCFERpgZKcm0j0fEq1YCJuyAWdz9KUtv1EjVuaOz8pDnh/0nZxmU6BBXwaaxqoi9PQXnRWqlcDB027hgv9A=="
      crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css"
      integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw=="
      crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}

{% block content %}
<div class="header">
    <a href="/create">
        <button type="button" class="btn btn-secondary float-end">New Blog</button>
    </a>
    <center>
        <h1 id="head">Blog</h1>
    </center>

</div>



<div class="container">

    <div class="row my-row align-items-around slider">

        {% for item in object_list %}
        <div class="col-md-6 col-xs-6 col-lg-4 " >
            <div class="card py-4" style="        width: 18rem;
        margin: 4%;
        position: relative;
        text-shadow: 1px 0 0 #fff, -1px 0 0 #fff, 0 1px 0 #fff, 0 -1px 0 #fff, 1px 1px #fff, -1px -1px 0 #fff, 1px -1px 0 #fff, -1px 1px 0 #fff;">
                {% if item.img %}
                <div>
                    <img src="{{item.img.url}}" class="img" />
                </div>
                {% endif %}
                <div class="card-body" style="position:relative">
                    <h5 class="card-title" >{{item.title|capfirst}} </h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{item.published_on}}</h6>
                    <p class="card-text">{{item.small_desc|capfirst}}</p>
                    <span style="text-shadow: 1px 0 0 #fff, -1px 0 0 #fff, 0 1px 0 #fff, 0 -1px 0 #fff, 1px 1px #fff, -1px -1px 0 #fff, 1px -1px 0 #fff, -1px 1px 0 #fff;">
                        <a href="{{item.pk}}" class="card-link">View</a>
                        <a href="{{item.pk}}/update" class="card-link">Update</a>
                        <a href="{{item.pk}}/delete" class="card-link">Delete</a>
                    </span>
                    
                    
                </div>
            </div>
        </div>
        {% endfor %}


    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"
        integrity="sha512-HGOnQO9+SP1V92SrtZfjqxxtLmVzqZpjFFekvzZVWoiASSQgSr4cw9Kqd2+l8Llp4Gm0G8GIFJ4ddwZilcdb8A=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script type="text/javascript">
    $('.slider').slick({
        dots: true,
        infinite: false,
        speed: 300,
        slidesToShow: 4,
        slidesToScroll: 4,
        responsive: [
            {
                breakpoint: 1024,
                settings: {
                    slidesToShow: 3,
                    slidesToScroll: 3,
                    infinite: true,
                    dots: true
                }
            },
            {
                breakpoint: 600,
                settings: {
                    slidesToShow: 2,
                    slidesToScroll: 2
                }
            },
            {
                breakpoint: 480,
                settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1
                }
            }
            // To unslick at a given breakpoint now by adding:
            // settings: "unslick"
            // instead of a settings object
        ]
    });
</script>
{% endblock %}

bolg/templates/update.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<style>
    body {
        padding: 5%;
        background-color: #E1E6E7;
        /*overflow-y:hidden;*/
    }
    .div-1 {
        margin-inline: auto;
        width: 40vw;
        background-color: #E1E1E1;
        padding: 2%;
        border-radius: 2%;
        box-shadow: 0px 5px 20px 2px #888888;
    }
</style>
{% endblock %}
{% block content %}

<div class="header">
    <a href="/">
        <button type="button" class="btn btn-secondary float-end">Home</button>
    </a>
    <center>
        <h1 style=" padding-bottom:2%;">Update your blog</h1>
    </center>

</div>


<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save" />
</form>


<!--formatted form-->
<!--div class="div-1">
    <form action="" method="POST" enctype="multipart/form-data">
        <input type="hidden" name="csrfmiddlewaretoken" value="AFHxEnHr1vfxMVEhcfGveXEr0cjriGnQIa3jfE5nkWXvR489OlACFMG8XdfXdOHo">
        <p><label for="id_title" class="col-sm-2 col-form-label">Title:</label> <input type="text" name="title" value="{{obj.title}}" maxlength="255" required id="id_title"></p>
        <p>
            <label for="id_small_desc" class="col-sm-2 col-form-label">Small desc:</label> <textarea name="small_desc" cols="40" rows="5" maxlength="400" required id="id_small_desc">
        {{obj.small_desc}}</textarea>
        </p>
        <p>
            <label for="id_full_content" class="col-sm-2 col-form-label"> Full content:</label> <textarea name="full_content" cols="40" rows="10" required id="id_full_content">
        {{obj.full_content}}</textarea>
        </p>
        <p>
            {% if obj.img %}
            <label for="id_img" class="col-sm-2 col-form-label">Img:</label> Currently: <a href="{{obj.img.url}}">current_img</a>
            <input type="checkbox" name="img-clear" id="img-clear_id">
            <label for="img-clear_id">Clear</label><br>
            Change:
            <input type="file" name="img" accept="image/*" id="id_img">
            {% else %}
            Add img: <input type="file" name="img" accept="image/*" id="id_img" />
            {% endif %}



        </p>
        <center><input type="submit" class="btn btn-success px-5 " value="Save" /></center>
    </form>
</div>-->


<!--formatted form-->



{% endblock %}